Haidra-Org/horde-worker-reGen

bridgeData_template.yaml, horde_worker_regen/process_management/process_manager.py, pyproject.toml
Critically the line:
https://github.com/Haidra-Org/horde-worker-reGen/blob/1fd531f20ca9b6e62e9ba130df49450b2b6b3578/horde_worker_regen/process_management/process_manager.py#L1406
Allows AWS S3 to not 403 when using aiohttp's PUT.
Many thanks to Avesia and robertcs from discord in solving this issue.
=> fix: job submit now async (await) call with aiohttp; minor log improvments

README.md
Has a disclaimer saying it might be outdated
=> add install steps from discord to readme

horde_worker_regen/process_management/inference_process.py, horde_worker_regen/process_management/worker_entry_points.py, run_worker.py
This will log exceptions with a stack trace that originate from hordelib.
=> fix: show stack trace on exception from within hordelib

horde_worker_regen/process_management/process_manager.py
fix: more elegant failover, default to txt2img earlier
fix: be less likely to crash on decompress. bomb attacks
fix: check source_image validation in more cases (such as when it was already passed as base64)
=> fix: handle source_image/mask failures better

horde_worker_regen/process_management/inference_process.py, horde_worker_regen/process_management/process_manager.py, requirements.txt
See https://github.com/Haidra-Org/hordelib/pull/132 for more information.
=> feat: support lora versioning

horde_worker_regen/process_management/horde_process.py, horde_worker_regen/process_management/process_manager.py, horde_worker_regen/process_management/worker_entry_points.py, requirements.txt
See https://github.com/Haidra-Org/hordelib/pull/143 for more information.
=> fix: image duplication issue squashed; better logging

.pre-commit-config.yaml, horde_worker_regen/process_management/process_manager.py, requirements.txt
- See https://github.com/Haidra-Org/hordelib/pull/145 for the hordelib changes helping prevent duplicate images.
- See https://github.com/Haidra-Org/AI-Horde/pull/338 and https://github.com/Haidra-Org/AI-Horde/pull/339 for the `bridge_agent`/`bridge_version` changes and the semver support.
=> fix: no longer produce duplicate images; feat: send semver bridge agent version

horde_worker_regen/process_management/process_manager.py, requirements.txt
See https://github.com/Haidra-Org/hordelib/pull/149 for more information.
=> fix: lora bug fixes

horde_worker_regen/process_management/process_manager.py, requirements.txt
see https://github.com/Haidra-Org/hordelib/pull/154 for more info
=> fix: lora name now matches as intended in more cases

horde_worker_regen/process_management/process_manager.py, requirements.118.txt, requirements.hordelib.txt, requirements.txt
see https://github.com/Haidra-Org/horde-sdk/pull/110 for more info
=> fix: use sdk which allows arbitrary samplers from API

download_models.py, horde_worker_regen/process_management/process_manager.py, requirements.txt
See https://github.com/Haidra-Org/hordelib/pull/159 for more information.
=> fix: fall-back to on-disk model references if they can't be downloaded

download_models.py
Closes https://github.com/Haidra-Org/horde-worker-reGen/issues/84
=> fix: redownload model on model ref entry change/update

horde_worker_regen/_version_meta.json
To support a future change which will permit notifying worker operators when updates are recommended or required.
=> feat: add version meta for update notifications

horde_worker_regen/process_management/process_manager.py
Bumps the client broadcast version (missed last release).
=> chore: version bump

horde_worker_regen/process_management/process_manager.py, requirements.txt
See https://github.com/Haidra-Org/horde-sdk/pull/144 for more information
=> fix: skipped mishap in sdk

horde_worker_regen/process_management/process_manager.py, requirements.txt
See https://github.com/Haidra-Org/hordelib/pull/193 for more info.
=> fix: use hordelib w/ model ref. retry

horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/process_management/process_manager.py, horde_worker_regen/version_meta.py, load_env_vars.py, tests/test_version_meta.py
This is to facilitate the upcoming cascade model reference change and hopefully also help in future beta testing, especially when the model reference changes in major ways.
=> feat: some version handling and beta model ref branch support

.gitignore, .pre-commit-config.yaml, horde-bridge.cmd, horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/bridge_data/data_model.py, horde_worker_regen/download_models.py, horde_worker_regen/load_env_vars.py, horde_worker_regen/process_management/inference_process.py, horde_worker_regen/process_management/main_entry_point.py, horde_worker_regen/process_management/messages.py, horde_worker_regen/process_management/process_manager.py, horde_worker_regen/process_management/worker_entry_points.py, horde_worker_regen/run_worker.py, mypy.ini, pyproject.toml, requirements.txt, tests/conftest.py, tests/test_horde_dep_updates.py, tests/test_pre_commit_dep_version.py
- LoRas can now download during the preload step whenever possible, hopefully limiting GPU core downtime
- Interprocess LoRa support has been improved which should hopefully minimize the amount of "forgotten" LoRas.
- Certain crashes surrounding fault handling have been fixed
- Tweaks have been made to performance and stability in general
- The console logging experience has been substantially improved:
- Log messages from long function names have been trimmed so log lines are not nearly as long on average.
- More and more useful information is printed in general
- The stats output messages have been reworked and improved (remember, you can adjust the frequency in seconds of this with stats_output_frequency)
- The default Windows `horde-bridge` script now attempts to download any …
=> feat: less lora download blocking; kudos training support

.github/workflows/maintests.yml, .github/workflows/prtests.yml
This should help catch changes to linting/mypy rules.
=> ci: run pre-commit with `--all-files`

README.md
I spent quite a few hours that I wouldn't have wasted if I'd known an SSD was needed. I suggest adding this to the README so others will know in advance.
=> Add workers' need for SSD to README

.pre-commit-config.yaml, horde-bridge.cmd, horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/process_management/process_manager.py, pyproject.toml, requirements.rocm.txt, requirements.txt
This will correctly report which image in a batch is censured and why. The order of job `ids` and `r2_uploads` needs to be fixed first, as discussed.
=> fix: correct report of censor

Dockerfiles/Dockerfile.cuda, Dockerfiles/Dockerfile.rocm
USER root, venv creation after clone (otherwise git complains) and COPY the setup scripts
With these in place the build runs successfully
=> minor fixes

.hadolint.yaml, .pre-commit-config.yaml, Dockerfiles/Dockerfile.cuda, Dockerfiles/Dockerfile.rocm
Introduces [hadolint](https://github.com/hadolint/hadolint) for Dockerfile linting and the relevant recommendations.
=> fix/style: hadolint Dockerfile lint fixes/recomendations

horde_worker_regen/process_management/process_manager.py
fix: Ensure correct image size is captured
feat: Store json files inside kudos_model_training/
feat: allow up to 10_000 json files instead of 100
=> fix: various tweaks on kudos model training data

README_advanced.md
We had a report about incompatibility between Ubuntu 24.04 and RDNA2 cards, apparently it works on 22.04
=> Use Ubuntu-22.04 explicitly

README.md, horde-bridge.cmd, preload-models.cmd, runtime.cmd, update-runtime.cmd
=> fix: mamba reungression

horde-bridge.sh
=> fix: fix Linux bridge invoking sudo automatically in warning message

.pre-commit-config.yaml, horde-bridge-directml.cmd, horde-bridge.cmd, horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/bridge_data/data_model.py, horde_worker_regen/bridge_data/load_config.py, horde_worker_regen/process_management/process_manager.py, pyproject.toml, requirements.directml.txt, requirements.rocm.txt, requirements.txt
- [fix: give 2 extra half ticks for process recovery to click](https://github.com/Haidra-Org/horde-worker-reGen/commit/e09b45dc2defd54f8a66f54b11c574fdbc619155)
- This might help avoid certain state desync issues surrounding process recovery
- [fix: use sdk w/ fix to model meta + large models](https://github.com/Haidra-Org/horde-worker-reGen/commit/82e8037715da92d204ced4757d7c84ff3c92ef64)
- This fixes the issue where flux/cascade did not load in all of the circumstances it should have
- [fix: show kudos/hr in limited_console_messages mode](https://github.com/Haidra-Org/horde-worker-reGen/commit/c2337b87fdf8ae663b26893c39b653b603e7c17f)
- [fix: less scary log message on R2 500s](https://github.com/Haidra-Org/horde-worker-reGen/commit/050ed03bcef877eaf45dbf0c2970157a3f017618)
- 500s are …
=> fix: V10 follow up fixes

README.md, horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/load_env_vars.py, horde_worker_regen/process_management/process_manager.py, pyproject.toml
- See https://github.com/Haidra-Org/AI-Horde/pull/479 for more information about API worker messages
- [docs: clarify custom model configuration and expectations](https://github.com/Haidra-Org/horde-worker-reGen/commit/46986ce163627672fe8ce8f1b0cc79b6176507db)
- This clarifies some additional information about custom models
- [fix: accurately report if default horde url is being used](https://github.com/Haidra-Org/horde-worker-reGen/commit/b4ccdc8be12ef0a658643030a47cdf678a300f28)
- A minor fix impacting a very small audience regarding a confusing debug-level log message during certain development or niche configuration situations.
=> feat: api worker message support
