Haidra-Org/horde-worker-reGen

horde_worker_regen/bridge_data/data_model.py, horde_worker_regen/bridge_data/load_config.py, load_env_vars.py, tests/test_bridge_data.py
This should fix the problem where worker names with extended characters were being mangled. I also suspect there would/could be other issues in a general sense without this change.
=> fix: read/write encoding for `open(...)` is now `utf-8`

.github/dependabot.yml
Use github's dependabot to regularly update pinned dependencies.
=> ci: feat: use dependabot

.pre-commit-config.yaml
Mypy was not analyzing types from imports, which was not intended.
=> ci: fix incorrectly configured mypy hook

.pre-commit-config.yaml, horde_worker_regen/process_management/inference_process.py, horde_worker_regen/process_management/messages.py, horde_worker_regen/process_management/process_manager.py, horde_worker_regen/process_management/safety_process.py, mypy.ini
Following up on #22:
- Introduced hordelib as a mypy pre-commit hook dep, allowing analysis of the types from that library.
- Fixed an import error that could occur with mypy (see mypy.ini)
- Resolved a couple of indev comments/messages in the code
- Refactored `_api_call_loop` to use asyncio tasks
- Made it so torch is loaded only in child processes, potentially avoiding some shared-resource confusion.
=> fix: minor fixes, tweaks, refactors

CONTRIBUTING.md
Adds a basic doc describing the code quality/formatting tools used in this project (and part of the CI).
=> docs: include contrib docs

horde_worker_regen/process_management/process_manager.py
On Linux, it seems like there is a tremendous amount of memory allocated by something outside Python when you allow one worker to process many jobs on many different models. In order to limit the damage from that behavior, we'll try to replace the processes when the model is scheduled to be unloaded.
I realize this probably makes it a _little_ harder to decouple a process from a model, but it's a huge stability improvement.
This also switches the model management strategy a tiny bit by allocating a model to every open worker before trying to unload a model. Previously, you would have
N processes = `threads` + `queue`, but jobs were very likely to be scheduled on only the `threads` number of workers.
=> Replace processes when a model is unloaded

download_models.py, load_env_vars.py
See https://github.com/Haidra-Org/hordelib/issues/128 for background.
- Actually sets [AIWORKER_LORA_CACHE_SIZE](https://github.com/Haidra-Org/horde-worker-reGen/commit/b39f7f2717b79089488fed71cdc19e3664a8997b) in the environment.
- [feat: add --purge-unused-loras to download_models.py](https://github.com/Haidra-Org/horde-worker-reGen/commit/883abac2008db07a288cbfb957fcfe922b99fae7)
=> fix: lora cache size issues

horde_worker_regen/bridge_data/data_model.py, horde_worker_regen/process_management/process_manager.py
For Windows users, killing the process before a model change seems wholly unnecessary.
I originally was cycling the processes to deal with the process size bloating to spectacular levels on Linux.
=> fix: make process cycling optional

horde_worker_regen/process_management/process_manager.py
Awaits an async function that wasn't awaited before, cuasing this error to occur if `image_in_buffer` is None
```py
horde_worker_regen\process_management\process_manager.py:2042: RuntimeWarning: coroutine 'GenericAsyncHordeAPISession.submit_request' was never awaited
await self.api_submit_job()
```
=> Await submit_request when setting follow_up_response

horde_worker_regen/process_management/process_manager.py
- The 5-minute halt dates back to when the worker was less stable and we were trying to minimize potential issues.
- The use of `time.sleep()` causes the in-process jobs to just abort because its blocking to the other coroutines. This is simply a bug at this point, and has to be changed.
- This change set will give the worker a chance to recover. If this goes on too long, the API will step in with maintenance mode.
=> fix: restart work after consecutive failed jobs; don't use time.sleep

bridgeData_template.yaml
Due to misunderstandings, including my own and other users, regarding the purpose of safety_on_gpu, I suggest a brief description.
=> docs: clarify what safety_on_gpu do

requirements.txt
Uses the `horde_model_reference` change ([see here](https://github.com/Haidra-Org/horde-model-reference/commit/0b91300a2bb21e7338a7cc57d9fd2e122491e9aa)) which prevents writing bad responses/error responses for downloads of model reference files (which should always be valid json). The net effect of this change should be that the most recent (valid) model reference would be used in the event the download (which happens every worker start) fails.
=> fix: use model reference version which handles dl fails better

horde_worker_regen/process_management/process_manager.py
Clarifies that the error pertains to `R2`/`S3` specifically, rather than a horde-hosted service.
=> fix: better message when R2 times out

.github/workflows/maintests.yml, .github/workflows/prtests.yml
This is a response to the recent tendency of the github runner to run out of disk space due to the duplication of python installs/environments with tox and pre-commit. This also should allow pull requests which are semantically valid to run the unit tests without halting for a simple whitespace or lint violation.
=> ci: split pre-commit to its own job; test python 3.11 too

horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, requirements.txt
Certain changes to the model reference now do not cause crashes
=> fix: use non-breaking model-ref library versions

.pre-commit-config.yaml, bridgeData_template.yaml, horde-bridge.cmd, horde_worker_regen/__init__.py, horde_worker_regen/bridge_data/load_config.py, pyproject.toml, requirements.txt, tests/test_bridge_data.py
As seen in the new template, the following will now work as valid `models_to_load` (or `models_to_skip`) instructions:
```
#
```
See https://github.com/Haidra-Org/horde-sdk/pull/155 for more info.
=> feat: support more model load instructions

.pre-commit-config.yaml, horde-bridge.cmd, horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/bridge_data/data_model.py, horde_worker_regen/load_env_vars.py, horde_worker_regen/process_management/inference_process.py, horde_worker_regen/process_management/process_manager.py, horde_worker_regen/version_meta.py, pyproject.toml, requirements.txt
- Sets the minimum required version of reGen to `4.2.4` due to the critical bug fixes it includes.
- Fixes a critical bug which occurs when a LoRa takes too long to download and can make the worker unstable
- Fixes LoRas retrying taking too long or retrying in doomed situations (such as missing a civitai token)
- Adds a fail-safe zombie detection:
- If all processes have done nothing (or no jobs were submitted) for the amount of time set by `process_timeout` (900 seconds by default) **AND** the last pop pop message was a valid job pop (and *not* a "no jobs" message)
- If `exit_on_unhandled_faults` is true
- The worker attempts to exit as quickly as possible, not reporting any faults.
- If `exit_on_unhandled_faults` is false (the default)
- All of the inference processes are restarted and …
=> feat: `exit_on_unhandled_faults` config option; attempt to recover (or exit) after too long a period of inactivity

.pre-commit-config.yaml, horde-bridge.cmd, horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/bridge_data/data_model.py, horde_worker_regen/process_management/process_manager.py, horde_worker_regen/run_worker.py, pyproject.toml, requirements.txt
- Fixes some issues when downloading LoRas and CivitAI acts unpredictably, experiences issues, or is excessively slow.
- See https://github.com/Haidra-Org/hordelib/pull/211 for a more detailed explanation.
- Tweaks the parameters surrounding the timing for job pops, which means that the worker should now only pop jobs at more reasonable times and that jobs will not be queued for any more time than is necessary. This shouldn't affect kudos/hr dramatically, but it should have a noticeable impact on the MPS ('performance') stat as seen on the `workers` stats endpoints.
- It should be noted that jobs that are bound by download speed will not always block the worker from working as of https://github.com/Haidra-Org/horde-worker-reGen/pull/139, and so being more conservative with the frequency …
=> fix: performance improvements; use hordelib w/ lora/ti metadata download fixes

.pre-commit-config.yaml, horde-bridge.cmd, requirements.txt
By way of https://github.com/Haidra-Org/horde-sdk/pull/176 this fixes a critical runtime error in horde_sdk which was the result of the changed handling of the `model_config` field used by pydantic as of 2.7.0. See the linked PR for more information.
=> fix: support pydantic 2.7.0

horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/process_management/process_manager.py, pyproject.toml
Some observed behavior on a worker machine indicates that the submit step has some code which may lead to worker lockups. I cannot fully account for the nature of those lockups, and this PR serves as an attempt to potentially resolve the problem, and in lieu of that, at least provide slightly more information to help root out the problem.
=> fix: handle more corner cases with job upload/submit

horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/process_management/process_manager.py, pyproject.toml
This should prevent crashes when QR code/CN workflows are used with custom models
=> fix: handle custom models in `keep_single_inference`

requirements.txt
As detailed [here](https://numpy.org/doc/stable/release/2.0.0-notes.html), v2.0.0 of numpy has numerous breaking changes. Notably, torch relies on numpy but does not support v2. This prevents new installs (or updates with the `-U` switch) from using this presently incompatible version of numpy.
=> fix: pin `numpy` to 1.26.4 (v2 is breaking)

.gitignore, .pre-commit-config.yaml, bridgeData_template.yaml, horde-bridge.cmd, horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/bridge_data/data_model.py, horde_worker_regen/download_models.py, horde_worker_regen/process_management/inference_process.py, horde_worker_regen/process_management/messages.py, horde_worker_regen/process_management/process_manager.py, horde_worker_regen/run_worker.py, pyproject.toml, requirements.dev.txt, requirements.rocm.txt, requirements.txt, tests/conftest.py, tests/test_pre_commit_dep_version.py, update-runtime.cmd
Requires: 
* https://github.com/Haidra-Org/hordelib/pull/272
* https://github.com/Haidra-Org/horde-sdk/pull/212
* https://github.com/Haidra-Org/AI-Horde-image-model-reference/pull/192
=> feat: Adds support for generating transparent images via layer diffusion

horde_worker_regen/bridge_data/data_model.py, horde_worker_regen/process_management/process_manager.py, horde_worker_regen/run_worker.py
- `AIWORKER_DREAMER_WORKER_NAME` will now override what is set for `dreamer_name`/`dreamer_worker_name` in `bridgeData.yaml`
- The `run_worker.py` cli arg `-w`/`--worker-name` has the same effect
- Note that this also applies to `horde-bridge.cmd` and `horde-bridge.sh` as the arguments passed to them are carried through to `run_worker.py`
=> feat: allow setting worker name via env var or cli arg

horde-bridge-rocm.sh, horde-bridge.sh, runtime-rocm.sh, runtime.sh, update-runtime-rocm.sh, update-runtime.sh
This allows your PWD do be used to isolate multiple configs and sets of logs when running more than one worker instance on a single machine
=> fix: run conda commands relative to linux script

horde_worker_regen/process_management/process_manager.py, horde_worker_regen/run_worker.py, preload-models.sh, update-runtime-rocm.sh, update-runtime.sh
As originally seen on the `amd` branch:
- Exit more aggressively when `exit_on_unhandled_faults: true`
- Fix the update-runtime*.sh scripts to work from arbitrary working directories to facilitate [ansible deployments](https://github.com/Haidra-Org/deployments)
- Fix ROCM version downloaded for AMD
=> fix: amd/linux script improvements; `exit_on_unhandled_faults` improvement

.pre-commit-config.yaml, bridgeData_template.yaml, horde-bridge.cmd, horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/bridge_data/data_model.py, pyproject.toml, requirements.rocm.txt, requirements.txt
The `load_large_models: false` configuration option prevents extremely heavy VRAM models (such as cascade or flux) from being included by default through meta commands such as TOP N or ALL.
=> feat: `load_large_models` for model meta

bridgeData_template.yaml, horde_worker_regen/load_env_vars.py
This causes the config option `horde_url` to work as expected. Previously, it was effectively ignored.
- Note that a check is made for the 'old' style URL, without the expected `/api/`, which was the previous default to allow for backwards compatibility. If known horde urls are detected, the SDK default value is used.
=> fix: set `AI_HORDE_URL` before horde_sdk import

horde_worker_regen/process_management/process_manager.py
It looks like the new info nsfw gen_metadata is created, but never added it to the list. This fixes that and adds it.
=> nsfw info gen_metadata fix

horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/process_management/process_manager.py, pyproject.toml
Currently the logic doesn't mark nsfw images with the information metadata if they were not censored. Changed it so that it marks them as NSFW always, but only if they were not censored.
The logic here is that the information here pertains to the actual content of the returned image, which in the case of censored images, is actually the SFW warning replacement. 
Supercedes #298
=> fix: mark all non-censored nsfw images in info

bridgeData_template.yaml, horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/bridge_data/data_model.py, horde_worker_regen/process_management/process_manager.py, pyproject.toml
- Sets default warning time for no jobs popped to 30 minutes combined.
- Clarifies the meaning of the warning associated with this message. It now reads:
> Your worker spent more than {minutes_allowed_without_jobs} minutes combined throughout this session ({cur_session_minutes:.2f} minutes) without jobs. This may be due to low demand. However, offering more models or increasing your max_power may help increase the number of jobs you receive and reduce downtime.
- Setting `suppress_speed_warnings: true` in your config will suppress this message from appearing.
=> fix: don't count time with any job popped as "no job" time; add way to suppress job time warnings

Dockerfiles/Dockerfile.12.1.1-22.04, Dockerfiles/Dockerfile.12.2.2-22.04, Dockerfiles/Dockerfile.12.3.2-22.04, Dockerfiles/Dockerfile.12.4-22.04
This was incomplete and masked by 22.04 also using 3.11 as it's Python version.
python3.11-dev is technically optional, but included because it's needed on the AMD side.
venv creation HAS to be called with the full version, otherwise the dist default is used.
pip only needs to be updated inside the venv.
This should be rather straight forward and just makes the dependencies explicit.
The current behavior won't change, but if the base python version (either of the OS, or what reGen is using)
ever changes, this version won't break. The old one would throw errors when trying to use the venv.
=> Fix installed python deps

runtime.cmd, update-runtime.cmd
It appears the micromamba cli args format changed at some point for manually entering the windows `venv`. This hotfix allows the convenience scripts for windows to work instead of failing with a cryptic `The following argument was not expected: -p` error.
=> fix: micromamba updated cli syntax for update-runtime

update-runtime.cmd
The change from `micromamba.bat` to `mamba.bat` isn't worth supporting backwards for. Running update-runtime already has the practical effect of reinstalling micromamba's conda venv, so it should be generally seen as safe to remove the directory as its rooted to the script folder and should otherwise be seen as managed by the worker code.
=> fix: delete conda dir and micromamba.exe if legacy version installed

update-runtime-rocm.sh
This fix is already present in the docker images I'm working on.
It appears to be a regression in torch 2.4.1 due to a conflict with `pynvml` and `nvidia-ml-py`
Reference:
https://github.com/vladmandic/automatic/issues/3181
=> amdsmi not found

Dockerfiles/README.md, Dockerfiles/compose.cuda.yaml
The `count: all` setting was missing, which was causing CUDA to be unavailable in some cases.
=> Fixed gpu configuration for compose.cuda.yaml

Dockerfiles/Dockerfile.cuda, Dockerfiles/Dockerfile.rocm, Dockerfiles/README.md, Dockerfiles/compose.cuda.yaml, Dockerfiles/compose.rocm.yaml, Dockerfiles/entrypoint.sh
This should allow the `docker stop` command to shut down the python process with SIGINT, allowing the process manager to stop the processes gracefully.
```bash
$ docker compose -f Dockerfiles/compose.cuda.yaml stop
[+] Stopping 1/1
✔ Container reGen  Stopped 
```
```bash
reGen  | 2024-11-01 01:53:44.889 | WARNING  | horde_worker_regen.process_management.process_manager:signal_handler:4162 - Shutting down after current jobs are finished...
reGen  | 2024-11-01 01:53:47.167 | INFO     | [HWRPM]:end_safety_processes:1516 - Ended safety process 0
reGen  | 2024-11-01 01:53:47.369 | INFO     | [HWRPM]:receive_and_handle_process_messages:1579 - Process 0 has ended with message: Process ended
reGen  | 2024-11-01 01:53:47.369 | INFO     | [HWRPM]:_process_control_loop:3793 - Shutting down process …
```
=> Use SIGINT to stop the docker container

Dockerfiles/compose.rocm.yaml, Dockerfiles/entrypoint.sh, Dockerfiles/setup_rocm.sh, horde-bridge-rocm.sh, horde_worker_regen/amd_go_fast/amd_go_fast.py, horde_worker_regen/amd_go_fast/install_amd_go_fast.sh, requirements.rocm.txt, update-runtime-rocm.sh
A newer (and less janky) version of flash_attn.
A bit more testing is required around changing the PyTorch version to 2.5.0 without breaking older setups.
Potential improvements:
- Skip installing flash_attn on compatiple cards if `FLASH_ATTENTION_USE_TRITON_ROCM=FALSE` (currently it's not build on old cards no matter what, but has to be set to true to avoid errors on compatible GPUs)
- Test 256 head dimensions (should be supported), might make FLUX.1 able to use it???
- Test if Triton makes the use of flash_attn possible on older RDNA cards possible
=> Flash Triton

Dockerfiles/entrypoint.sh, horde-bridge-rocm.sh, horde_worker_regen/amd_go_fast/install_amd_go_fast.sh, update-runtime-rocm.sh
This patch makes it possible to overwrite the compatibility check.
It enables flash_attn testing on older cards without having the tester dig through the code.
It also fixes a bug in the `entrypoint.sh`, that would cause flash_attn to not build on supported systems if the env variable was unset.
=> Fix FLASH_ATTENTION_USE_TRITON_ROCM export

Dockerfiles/compose.cuda.yaml, Dockerfiles/compose.rocm.yaml
This should be a useful default so that logs aren't immediately lost when for example the docker container crashes.
=> Mount logs directory to docker

horde_worker_regen/amd_go_fast/install_amd_go_fast.sh
If we want to test whether this works on new systems, it should clean up after itself if the overwride is no longer present.
=> remove GO_FAST if support is not present

README.md, README_advanced.md, horde-bridge-rocm.sh, update-runtime-rocm.sh
This is a first draft. Feedback on the clarity of descriptions, level of detail and questions left open is welcome.
The WSL-Patch needs a bit more testing to make sure it runs reliably.
flash_attn integration is also flaky as of now.
Memory usage, as usual on Linux systems is suboptimal, WSL memory overhead makes this even more obvious.
=> ROCm in WSL

.pre-commit-config.yaml, horde-bridge.cmd, horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/process_management/process_manager.py, pyproject.toml, requirements.rocm.txt, requirements.txt, tests/test_sdk_models.py
Previously, unknown reasons would not show due to the SDK model not having them. However, with `model_extra`, this information is present and just needs to be shown to the user
Additionally, I've added code to remove the '0' values as they are generally uninteresting.
=> fix: skipped reasons missing

Dockerfiles/compose.rocm.yaml, horde-bridge-rocm.sh, horde_worker_regen/amd_go_fast/install_amd_go_fast.sh, update-runtime-rocm.sh
These are some small logical oversights after updating the compatibility check and including cleanup in case flash_attn is later removed. We don't want to manually overwrite the compatibility check in the `compose.yaml` by default.
Also, without `rm -f` Docker doesn't wanna start if `FLASH_ATTN=FALSE`, because technically an `rm` on a non existant file is an unsuccessful command.
Split out from #358, since that is more complex and requires some extra testing.
=> Go fast fix minor

update-runtime.cmd
This resolves the immediate issue and should avoid this sort of mismatch in the future. If a specific torchvision pin ends up being necessary again in the future I'll deal with it more robustly then.
=> build/fix: remove unnecessary torchvision pin

README.md, bridgeData_template.yaml, horde_worker_regen/process_management/process_manager.py, tests/test_sdk_models.py
Nowhere in the README or the bridge data template did it mention that the worker names needed to be unique.  However, using the default names led to the error "Wrong credentials to submit as this worker."  I found the cause on Reddit.
This adds brief notes to both the README and the template file to try to guide people explicitly on this point.  Had these notes been present, I would not have made the mistake of keeping the defaults.
=> docs: Fix missing setup instructions

README.md, README_advanced.md, download_models.py, horde-bridge-directml.cmd, horde_worker_regen/download_models.py, horde_worker_regen/process_management/main_entry_point.py, horde_worker_regen/process_management/process_manager.py, horde_worker_regen/process_management/worker_entry_points.py, horde_worker_regen/run_worker.py, requirements.directml.txt, tests/conftest.py, tests/test_horde_dep_updates.py, update-runtime-directml.cmd
This should broaden our compatibility, although with significantly worse performance than native libraries.
ToDo:
**Worse Performance shold be documented and advised against, before announcing this.**
The PR still needs the knobs and dials to only enable directml under certain conditions, easiest would be an eqivalent to `--amd` and then maybe another initialization script?
Or maybe think about a way to properly detect what plattform we are running on and go from there?
Having 4 different `update-runtime` scripts mostly doing the same is getting a bit out of hand...
=> enable directml

.gitignore, .pre-commit-config.yaml, bridgeData_template.yaml, horde-bridge-directml.cmd, horde-bridge.cmd, horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/bridge_data/data_model.py, horde_worker_regen/load_env_vars.py, horde_worker_regen/process_management/horde_process.py, horde_worker_regen/process_management/inference_process.py, horde_worker_regen/process_management/messages.py, horde_worker_regen/process_management/process_manager.py, horde_worker_regen/process_management/worker_entry_points.py, horde_worker_regen/run_worker.py, pyproject.toml, requirements.dev.txt, requirements.directml.txt, requirements.rocm.txt, requirements.txt
What originally was supposed to be a set of minor bug fixes has turned into a major version update. You will immediately notice a difference in the console messages, which have been totally reworked for readability and clarity. Hopefully, over longer periods of time, you will also notice that the worker is significantly more stable, and for many users, faster.
Additionally, v10.0.0 offers other enhancements, such as reintroducing high_memory_mode, improving max_threads > 1 viability (even for low VRAM gpus), and resolving batching and deadlock issues. Job handling and status reporting have been refined, and the update includes multiple fixes and improvements to the LoRA and Textual Inversion systems.
A detailed list of changes follows:
* A (baffling) [breakthrough …
=> fix: memory and lora cache improvements

horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/process_management/inference_process.py, horde_worker_regen/process_management/process_manager.py, pyproject.toml
Too many warnings may lead to confusion to this otherwise normal condition. This will probably require further refining and there are much more sophisticated ways to go about this.
=> fix: be a little more forgiving with it/s on batched jobs

Dockerfiles/compose.rocm.yaml, Dockerfiles/entrypoint.sh, horde-bridge-rocm.sh, horde_worker_regen/amd_go_fast/install_amd_go_fast.sh, update-runtime-rocm.sh
These were held up behind https://github.com/Haidra-Org/horde-worker-reGen/pull/358, but apparently broke recently.
The ENV variable was renamed, so change that and switch to the official upstream implementation while we're at it.
This should be functionally identical, except well... not broken any more.
=> flash_attn upstream

horde_worker_regen/__init__.py, horde_worker_regen/_version_meta.json, horde_worker_regen/process_management/process_manager.py, horde_worker_regen/process_management/worker_entry_points.py, pyproject.toml
- [fix: avoid crash w/ remove maint flag if worker didn't exist](https://github.com/Haidra-Org/horde-worker-reGen/commit/119cdc0516dbe88c5d31c4d72a595bc350b97354)
- The worker is only registered after the first job pop. Prior to this change, if the worker operator happens to have this set when changing worker name, the worker would crash and exit on start up. As this isn't really an unrecoverable scenario (we can just skip exiting maint mode in this case), I've added a try/except to warn on whatever did happen but to continue anyway.
- [fix: reserve extra vram with high vram models](https://github.com/Haidra-Org/horde-worker-reGen/commit/e67bd8cb04df3ed27cb4296eafc59930c8f9e39d)
- This makes it so if `high_memory_mode` is on and there are big models (flux, cascade), a total of 6gb of VRAM …
=> fix: avoid crash w/ remove maint flag; fix: reserve extra vram with high vram models  
